//! sea-orm entities for `meta_cache.sqlite`.
//!
//! Hand-written (not generated by `sea-orm-cli`) because the schema is
//! small and stable. The five files below mirror the five tables
//! declared in `migration::Migration`.

pub mod exif_cache;
pub mod histogram_cache;
pub mod image_metadata;
pub mod image_tags;
pub mod tags;
